"""
MAME Hot-Swap — Ephemeral Controller Configuration Injection

Instead of overwriting MAME's default.cfg (risky, permanent), this service
writes a temporary controller profile to the ctrlr/ directory. MAME reads
it via the -ctrlr flag, leaving the default config untouched.

Architecture:
  Chuck Panel → POST /mame-config/hot-swap → write_ephemeral_config()
  → Emulators/MAME/ctrlr/live_session.cfg → MAME -ctrlr live_session

The ephemeral file uses the same <mameconfig version="10"> XML schema
as default.cfg, generated by the existing mame_config_generator module.

Safety:
  - Never touches default.cfg
  - File can be deleted at any time without consequence
  - If file is missing when MAME launches, -ctrlr silently ignored
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from backend.services.mame_config_generator import (
    generate_mame_config,
    validate_mame_config,
    get_mame_config_summary,
    MAMEConfigError,
)

logger = logging.getLogger(__name__)

# Ephemeral config filename — referenced by MAME's -ctrlr flag
EPHEMERAL_PROFILE_NAME = "live_session"
EPHEMERAL_FILENAME = f"{EPHEMERAL_PROFILE_NAME}.cfg"

# Relative path from drive root to the MAME ctrlr directory
CTRLR_REL_PATH = Path("Emulators") / "MAME" / "ctrlr"


def _get_ctrlr_dir(drive_root: Path) -> Path:
    """Resolve the MAME ctrlr directory from drive root."""
    return drive_root / CTRLR_REL_PATH


def _get_ephemeral_path(drive_root: Path) -> Path:
    """Full path to the ephemeral config file."""
    return _get_ctrlr_dir(drive_root) / EPHEMERAL_FILENAME


def write_ephemeral_config(
    mapping_data: Dict[str, Any],
    drive_root: Path,
) -> Dict[str, Any]:
    """
    Generate and write an ephemeral MAME controller config.

    Reuses the existing generate_mame_config() pipeline so the XML schema
    is identical to what default.cfg would contain — just written to the
    ctrlr/ directory instead.

    Args:
        mapping_data: The controls.json mapping dictionary.
        drive_root: Root path of the A: drive (from app.state.drive_root).

    Returns:
        Dict with status, file path, summary, and validation info.

    Raises:
        MAMEConfigError: If XML generation fails.
        ValueError: If validation produces errors.
    """
    ephemeral_path = _get_ephemeral_path(drive_root)

    # Generate MAME config XML using the proven generator
    xml_content = generate_mame_config(mapping_data)

    # Validate before writing
    validation_errors = validate_mame_config(xml_content)
    if validation_errors:
        raise ValueError(
            f"Ephemeral config failed validation: {', '.join(validation_errors)}"
        )

    # Ensure ctrlr directory exists
    ephemeral_path.parent.mkdir(parents=True, exist_ok=True)

    # Write the ephemeral config
    with open(ephemeral_path, "w", encoding="utf-8") as f:
        f.write(xml_content)

    summary = get_mame_config_summary(xml_content)
    timestamp = datetime.now(timezone.utc).isoformat()

    logger.info(
        "Wrote ephemeral MAME config: %s (%d ports)",
        ephemeral_path,
        summary.get("port_count", 0),
    )

    return {
        "status": "active",
        "profile_name": EPHEMERAL_PROFILE_NAME,
        "file_path": str(ephemeral_path),
        "relative_path": str(CTRLR_REL_PATH / EPHEMERAL_FILENAME),
        "timestamp": timestamp,
        "summary": summary,
        "validation": {"valid": True, "errors": []},
        "mame_flag": f"-ctrlr {EPHEMERAL_PROFILE_NAME}",
    }


def clear_ephemeral_config(drive_root: Path) -> Dict[str, Any]:
    """
    Remove the ephemeral config file.

    Safe to call even if the file doesn't exist.

    Args:
        drive_root: Root path of the A: drive.

    Returns:
        Dict with status and whether the file was actually removed.
    """
    ephemeral_path = _get_ephemeral_path(drive_root)

    was_present = ephemeral_path.exists()
    if was_present:
        ephemeral_path.unlink()
        logger.info("Cleared ephemeral MAME config: %s", ephemeral_path)
    else:
        logger.debug("No ephemeral config to clear at %s", ephemeral_path)

    return {
        "status": "cleared",
        "was_active": was_present,
        "file_path": str(ephemeral_path),
    }


def get_ephemeral_status(drive_root: Path) -> Dict[str, Any]:
    """
    Check whether an ephemeral config is currently active.

    Args:
        drive_root: Root path of the A: drive.

    Returns:
        Dict with active flag, file info, and summary if active.
    """
    ephemeral_path = _get_ephemeral_path(drive_root)

    if not ephemeral_path.exists():
        return {
            "active": False,
            "profile_name": EPHEMERAL_PROFILE_NAME,
            "file_path": str(ephemeral_path),
            "mame_flag": f"-ctrlr {EPHEMERAL_PROFILE_NAME}",
        }

    # Read and summarize the existing file
    try:
        xml_content = ephemeral_path.read_text(encoding="utf-8")
        summary = get_mame_config_summary(xml_content)
        validation_errors = validate_mame_config(xml_content)
        stat = ephemeral_path.stat()
        modified = datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat()
    except Exception as e:
        logger.warning("Failed to read ephemeral config: %s", e)
        return {
            "active": True,
            "profile_name": EPHEMERAL_PROFILE_NAME,
            "file_path": str(ephemeral_path),
            "error": str(e),
        }

    return {
        "active": True,
        "profile_name": EPHEMERAL_PROFILE_NAME,
        "file_path": str(ephemeral_path),
        "relative_path": str(CTRLR_REL_PATH / EPHEMERAL_FILENAME),
        "modified": modified,
        "size_bytes": stat.st_size,
        "summary": summary,
        "validation": {
            "valid": len(validation_errors) == 0,
            "errors": validation_errors,
        },
        "mame_flag": f"-ctrlr {EPHEMERAL_PROFILE_NAME}",
    }
