"""RetroArch Configuration Generator

Generates RetroArch .cfg files from Console Wizard controller profiles.
Supports Xbox, PlayStation, and Nintendo Switch controllers with proper
button mappings, analog deadzone configuration, and hotkey assignments.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class RetroArchConfigError(Exception):
    """Raised when RetroArch config generation fails"""
    pass


class RetroArchValidationError(RetroArchConfigError):
    """Raised when RetroArch config validation fails"""
    pass


@dataclass(frozen=True)
class HotkeyMapping:
    """Standard RetroArch hotkey assignments"""
    menu_toggle: str = "6+7"  # Select + Start
    save_state: str = "6+5"   # Select + R1
    load_state: str = "6+4"   # Select + L1
    fast_forward: str = "6+7" # Select + R2 (mapped to triggers if available)
    rewind: str = "6+6"       # Select + L2
    screenshot: str = "6+3"   # Select + Y
    pause: str = "6+9"        # Select + Guide/Home
    reset: str = "6+2"        # Select + X


def generate_retroarch_config(
    profile: Dict[str, Any],
    player: int = 1,
    system: Optional[str] = None,
    include_hotkeys: bool = True,
    include_deadzones: bool = True
) -> str:
    """Generate RetroArch .cfg file content from controller profile

    Args:
        profile: Controller profile dictionary (loaded from JSON)
        player: Player number (1-4)
        system: Optional system override (e.g., 'snes', 'genesis', 'ps1')
        include_hotkeys: Include hotkey mappings (menu, save/load state, etc.)
        include_deadzones: Include analog deadzone settings

    Returns:
        RetroArch .cfg file content as string

    Raises:
        RetroArchConfigError: If profile is invalid or generation fails
        RetroArchValidationError: If player number is out of range

    Example:
        >>> profile = load_profile('xbox_360')
        >>> cfg_content = generate_retroarch_config(profile, player=1)
        >>> # Write to file: config/retroarch/xbox_360_p1.cfg
    """
    try:
        # Validate player number range
        if not 1 <= player <= 4:
            raise RetroArchValidationError(
                f"Player number must be 1-4, got {player}"
            )

        # Validate profile structure
        required_keys = ['name', 'retroarch_defaults']
        missing_keys = [key for key in required_keys if key not in profile]
        if missing_keys:
            raise RetroArchConfigError(
                f"Profile missing required keys: {', '.join(missing_keys)}"
            )

        # Start building config lines
        config_lines = []

        # Header comment
        config_lines.append(f"# RetroArch Controller Configuration")
        config_lines.append(f"# Profile: {profile['name']}")
        config_lines.append(f"# Player: {player}")
        if system:
            config_lines.append(f"# System: {system.upper()}")
        config_lines.append(f"# Generated by Arcade Assistant - Console Wizard")
        config_lines.append("")

        # Device identification
        device_name = profile.get('name', 'Unknown Controller')
        config_lines.append(f'input_device = "{device_name}"')
        config_lines.append("")

        # Get RetroArch defaults from profile
        retroarch_defaults = profile.get('retroarch_defaults', {})

        if not retroarch_defaults:
            logger.warning(f"Profile {profile.get('profile_id')} has no retroarch_defaults")

        # Hotkey keys that will be generated separately
        HOTKEY_KEYS = {
            'input_menu_toggle_btn',
            'input_save_state_btn',
            'input_load_state_btn',
            'input_screenshot_btn',
            'input_pause_toggle_btn',
            'input_reset_btn',
            'input_fast_forward_btn',
            'input_rewind_btn'
        }

        # Apply player number substitution to base mappings
        # Convert input_player1_* to input_player{player}_*
        player_mappings = {}
        for key, value in retroarch_defaults.items():
            # Skip the input_device key (already added)
            if key == 'input_device':
                continue

            # Skip hotkey keys if we're generating them separately
            if include_hotkeys and key in HOTKEY_KEYS:
                continue

            # Replace player1 with actual player number
            if 'player1' in key:
                new_key = key.replace('player1', f'player{player}')
                player_mappings[new_key] = value
            else:
                player_mappings[key] = value

        # Single-pass key categorization for better performance
        button_keys = []
        axis_keys = []
        for key in player_mappings.keys():
            if '_btn' in key:
                button_keys.append(key)
            elif '_axis' in key:
                axis_keys.append(key)

        # Add button mappings
        config_lines.append("# Button Mappings")
        for key in sorted(button_keys):
            value = player_mappings[key]
            config_lines.append(f'{key} = "{value}"')

        config_lines.append("")

        # Add axis mappings
        config_lines.append("# Analog Axis Mappings")
        for key in sorted(axis_keys):
            value = player_mappings[key]
            config_lines.append(f'{key} = "{value}"')

        config_lines.append("")

        # Add deadzone settings if requested
        if include_deadzones and 'axes' in profile:
            config_lines.append("# Analog Deadzone Settings")
            axes = profile.get('axes', {})

            # Extract deadzone values from profile
            deadzones = {}
            for axis_name, axis_data in axes.items():
                if isinstance(axis_data, dict) and 'deadzone' in axis_data:
                    deadzones[axis_name] = axis_data['deadzone']

            # Apply deadzones
            if deadzones:
                # Left analog stick deadzone
                if 'left_stick_x' in deadzones or 'left_stick_y' in deadzones:
                    deadzone = deadzones.get('left_stick_x', 0.15)
                    config_lines.append(f'input_player{player}_analog_dpad_mode = "0"')
                    config_lines.append(f'input_player{player}_l_x_deadzone = "{deadzone}"')
                    config_lines.append(f'input_player{player}_l_y_deadzone = "{deadzone}"')

                # Right analog stick deadzone
                if 'right_stick_x' in deadzones or 'right_stick_y' in deadzones:
                    deadzone = deadzones.get('right_stick_x', 0.15)
                    config_lines.append(f'input_player{player}_r_x_deadzone = "{deadzone}"')
                    config_lines.append(f'input_player{player}_r_y_deadzone = "{deadzone}"')

                config_lines.append("")

        # Add hotkey mappings if requested (only for player 1)
        if include_hotkeys and player == 1:
            config_lines.append("# Hotkey Mappings")
            config_lines.append("# Combo: Select + Button")

            hotkeys = HotkeyMapping()

            config_lines.append(f'input_menu_toggle_btn = "{hotkeys.menu_toggle}"')
            config_lines.append(f'input_save_state_btn = "{hotkeys.save_state}"')
            config_lines.append(f'input_load_state_btn = "{hotkeys.load_state}"')
            config_lines.append(f'input_screenshot_btn = "{hotkeys.screenshot}"')
            config_lines.append(f'input_pause_toggle_btn = "{hotkeys.pause}"')
            config_lines.append(f'input_reset_btn = "{hotkeys.reset}"')
            config_lines.append("")

        # Add system-specific overrides if provided
        if system:
            config_lines.append(f"# System-Specific Overrides: {system.upper()}")
            config_lines.append("# (System overrides would go here in future enhancement)")
            config_lines.append("")

        # Join all lines (deduplicate keys defensively)
        seen = set()
        deduped = []
        for ln in config_lines:
            stripped = ln.strip()
            # Only check non-empty, non-comment lines for duplicates
            if stripped and not stripped.startswith('#') and '=' in stripped:
                k = stripped.split('=', 1)[0].strip()
                if k in seen:
                    continue  # Skip duplicate key
                seen.add(k)
            deduped.append(ln)
        config_content = '\n'.join(deduped)

        return config_content

    except RetroArchValidationError:
        # Re-raise validation errors as-is
        raise
    except KeyError as e:
        raise RetroArchConfigError(f"Missing required profile field: {str(e)}")
    except ValueError as e:
        raise RetroArchValidationError(f"Invalid value in profile: {str(e)}")
    except Exception as e:
        logger.error(f"Unexpected error in config generation: {e}", exc_info=True)
        raise RetroArchConfigError(f"Failed to generate RetroArch config: {str(e)}")


def validate_retroarch_config(config_content: str) -> List[str]:
    """Validate RetroArch .cfg file content

    Checks for:
    - Required input_device line
    - Valid key=value format
    - Presence of button/axis mappings
    - No duplicate keys

    Args:
        config_content: RetroArch .cfg file content

    Returns:
        List of validation error messages (empty if valid)

    Example:
        >>> errors = validate_retroarch_config(cfg_content)
        >>> if errors:
        ...     print(f"Validation failed: {errors}")
        ... else:
        ...     print("Config is valid")
    """
    errors = []

    if not config_content or not config_content.strip():
        errors.append("Config content is empty")
        return errors

    lines = config_content.split('\n')
    config_keys = set()
    has_device = False
    has_buttons = False
    has_axes = False

    for line_num, line in enumerate(lines, start=1):
        # Skip comments and empty lines
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue

        # Check for key=value format
        if '=' not in line:
            errors.append(f"Line {line_num}: Invalid format (missing '='): {line}")
            continue

        # Parse key=value
        try:
            key_part, value_part = line.split('=', 1)
            key = key_part.strip()
            value = value_part.strip()

            # Check for empty key or value
            if not key:
                errors.append(f"Line {line_num}: Empty key")
            if not value:
                errors.append(f"Line {line_num}: Empty value for key '{key}'")

            # Check for duplicate keys
            if key in config_keys:
                errors.append(f"Line {line_num}: Duplicate key '{key}'")
            config_keys.add(key)

            # Check for required elements
            if key == 'input_device':
                has_device = True
            if '_btn' in key:
                has_buttons = True
            if '_axis' in key:
                has_axes = True

        except ValueError:
            errors.append(f"Line {line_num}: Invalid key=value format: {line}")

    # Check for required elements
    if not has_device:
        errors.append("Missing required 'input_device' line")

    if not has_buttons and not has_axes:
        errors.append("No button or axis mappings found")

    return errors


def get_retroarch_config_summary(config_content: str) -> Dict[str, Any]:
    """Extract summary information from RetroArch config content

    Args:
        config_content: RetroArch .cfg file content

    Returns:
        Dictionary with config summary (button count, axis count, etc.)

    Example:
        >>> summary = get_retroarch_config_summary(cfg_content)
        >>> print(f"Device: {summary['device_name']}")
        >>> print(f"Buttons: {summary['button_count']}")
    """
    summary = {
        "valid": False,
        "device_name": "Unknown",
        "player": None,
        "system": None,
        "button_count": 0,
        "axis_count": 0,
        "has_deadzones": False,
        "has_hotkeys": False,
        "total_lines": 0,
        "config_keys": []
    }

    try:
        lines = config_content.split('\n')
        summary["total_lines"] = len(lines)

        button_keys = []
        axis_keys = []
        deadzone_keys = []
        hotkey_keys = []

        for line in lines:
            stripped = line.strip()

            # Skip comments and empty lines
            if not stripped or stripped.startswith('#'):
                # Try to extract metadata from comments
                if '# Player:' in line:
                    try:
                        summary["player"] = int(line.split('Player:')[1].strip())
                    except (IndexError, ValueError):
                        pass
                if '# System:' in line:
                    try:
                        summary["system"] = line.split('System:')[1].strip()
                    except IndexError:
                        pass
                continue

            if '=' not in line:
                continue

            key_part, value_part = line.split('=', 1)
            key = key_part.strip()
            value = value_part.strip().strip('"')

            summary["config_keys"].append(key)

            # Extract device name
            if key == 'input_device':
                summary["device_name"] = value

            # Count buttons
            if '_btn' in key and not key.startswith('input_menu') and not key.startswith('input_save') and not key.startswith('input_load'):
                button_keys.append(key)

            # Count axes
            if '_axis' in key and 'deadzone' not in key:
                axis_keys.append(key)

            # Check for deadzones
            if 'deadzone' in key:
                deadzone_keys.append(key)

            # Check for hotkeys
            if key in ['input_menu_toggle_btn', 'input_save_state_btn',
                      'input_load_state_btn', 'input_screenshot_btn']:
                hotkey_keys.append(key)

        summary["button_count"] = len(button_keys)
        summary["axis_count"] = len(axis_keys)
        summary["has_deadzones"] = len(deadzone_keys) > 0
        summary["has_hotkeys"] = len(hotkey_keys) > 0
        summary["valid"] = summary["button_count"] > 0 or summary["axis_count"] > 0

    except Exception as e:
        logger.error(f"Failed to generate RetroArch config summary: {e}")

    return summary


# Module-level test function
def main() -> None:
    """Run RetroArch config generator tests"""
    print("RetroArch Config Generator Test")
    print("=" * 60)

    # Test profile (minimal Xbox 360 structure)
    test_profile = {
        "profile_id": "xbox_360",
        "name": "Xbox 360 Controller",
        "manufacturer": "Microsoft",
        "type": "console_gamepad",
        "buttons": {
            "a": {"index": 0, "label": "A"},
            "b": {"index": 1, "label": "B"}
        },
        "dpad": {},
        "axes": {
            "left_stick_x": {"index": 0, "label": "Left Stick X", "deadzone": 0.15},
            "left_stick_y": {"index": 1, "label": "Left Stick Y", "deadzone": 0.15},
            "right_stick_x": {"index": 2, "label": "Right Stick X", "deadzone": 0.15},
            "right_stick_y": {"index": 3, "label": "Right Stick Y", "deadzone": 0.15}
        },
        "retroarch_defaults": {
            "input_device": "Xbox 360 Controller",
            "input_player1_b_btn": "0",
            "input_player1_y_btn": "2",
            "input_player1_select_btn": "6",
            "input_player1_start_btn": "7",
            "input_player1_up_btn": "h0up",
            "input_player1_down_btn": "h0down",
            "input_player1_left_btn": "h0left",
            "input_player1_right_btn": "h0right",
            "input_player1_a_btn": "1",
            "input_player1_x_btn": "3",
            "input_player1_l_btn": "4",
            "input_player1_r_btn": "5",
            "input_player1_l2_axis": "+4",
            "input_player1_r2_axis": "+5",
            "input_player1_l3_btn": "8",
            "input_player1_r3_btn": "9",
            "input_player1_l_x_plus_axis": "+0",
            "input_player1_l_x_minus_axis": "-0",
            "input_player1_l_y_plus_axis": "+1",
            "input_player1_l_y_minus_axis": "-1",
            "input_player1_r_x_plus_axis": "+2",
            "input_player1_r_x_minus_axis": "-2",
            "input_player1_r_y_plus_axis": "+3",
            "input_player1_r_y_minus_axis": "-3"
        }
    }

    try:
        print("\nGenerating RetroArch config for Player 1...")
        cfg_content = generate_retroarch_config(test_profile, player=1)

        print("\nGenerated Config (first 30 lines):")
        print("-" * 60)
        lines = cfg_content.split('\n')[:30]
        for line in lines:
            print(line)
        if len(cfg_content.split('\n')) > 30:
            print("... (truncated)")

        print("\n" + "=" * 60)
        print("\nValidating generated config...")
        errors = validate_retroarch_config(cfg_content)

        if errors:
            print(f"Validation FAILED with {len(errors)} error(s):")
            for error in errors:
                print(f"  - {error}")
        else:
            print("Validation PASSED - Config is well-formed")

        print("\n" + "=" * 60)
        print("\nConfig Summary:")
        summary = get_retroarch_config_summary(cfg_content)
        print(f"  Valid: {summary['valid']}")
        print(f"  Device: {summary['device_name']}")
        print(f"  Player: {summary['player']}")
        print(f"  Button Count: {summary['button_count']}")
        print(f"  Axis Count: {summary['axis_count']}")
        print(f"  Has Deadzones: {summary['has_deadzones']}")
        print(f"  Has Hotkeys: {summary['has_hotkeys']}")
        print(f"  Total Lines: {summary['total_lines']}")

        print("\n" + "=" * 60)
        print("\nTest PASSED - RetroArch config generator is operational")

    except RetroArchConfigError as e:
        print(f"\nERROR: {e}")


if __name__ == "__main__":
    main()
