@echo off
REM ========================================
REM Arcade Assistant - Cabinet Installation
REM ========================================
REM This script sets up Arcade Assistant on a new cabinet PC
REM Prerequisites: Node.js v18+, Python 3.10+, A: drive accessible

color 0A
echo.
echo ========================================
echo   ARCADE ASSISTANT
echo   Cabinet Installation Script
echo ========================================
echo.

REM Check for Administrator privileges
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [WARNING] Not running as Administrator
    echo Some features may not work correctly.
    echo Right-click this file and select "Run as Administrator"
    echo.
    pause
)

REM ----------------------------------------
REM STEP 1: Check Prerequisites
REM ----------------------------------------
echo [1/8] Checking prerequisites...
echo.

REM Check Node.js
where node >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Node.js not found!
    echo.
    echo Please install Node.js v18 or higher from:
    echo https://nodejs.org/
    echo.
    pause
    exit /b 1
) else (
    for /f "tokens=*" %%i in ('node --version') do set NODE_VERSION=%%i
    echo [OK] Node.js found: %NODE_VERSION%
)

REM Check Python
where python >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Python not found!
    echo.
    echo Please install Python 3.10 or higher from:
    echo https://python.org/
    echo.
    pause
    exit /b 1
) else (
    for /f "tokens=*" %%i in ('python --version') do set PYTHON_VERSION=%%i
    echo [OK] Python found: %PYTHON_VERSION%
)

REM Derive drive root from script location (enables clone-to-any-drive workflow)
set "AA_SCRIPT_DRIVE=%~d0"
if not exist "%AA_SCRIPT_DRIVE%\" (
    echo [ERROR] Cannot access script drive: %AA_SCRIPT_DRIVE%
    pause
    exit /b 1
)
echo [OK] Script drive accessible: %AA_SCRIPT_DRIVE%

echo.
echo ----------------------------------------
echo Prerequisites check complete!
echo ----------------------------------------
echo.
pause

REM ----------------------------------------
REM STEP 2: Device Serialization
REM ----------------------------------------
echo.
echo [2/8] Device Serialization
echo.
echo This cabinet needs a unique serial number.
echo Example: AA-0001, AA-0002, AA-0003, etc.
echo.

set /p DEVICE_SERIAL="Enter cabinet serial number (e.g., AA-0001): "
if "%DEVICE_SERIAL%"=="" (
    echo [ERROR] Serial number is required!
    pause
    exit /b 1
)

set /p DEVICE_NAME="Enter cabinet name (e.g., Basement Cabinet 1): "
if "%DEVICE_NAME%"=="" (
    set DEVICE_NAME=Arcade Cabinet %DEVICE_SERIAL%
)

echo.
echo Device Serial: %DEVICE_SERIAL%
echo Device Name: %DEVICE_NAME%
echo.
echo This information will be saved to .env file.
echo.
pause

REM ----------------------------------------
REM STEP 3: Create .env file
REM ----------------------------------------
echo.
echo [3/8] Creating environment configuration...
echo.

if not exist .env.template (
    echo [WARNING] .env.template not found!
    echo Creating basic .env file...

    REM Create minimal .env
    (
        echo # Arcade Assistant Environment Configuration
        echo # Generated by install-cabinet.bat on %DATE% at %TIME%
        echo.
        echo # Device Identification
        echo DEVICE_SERIAL=%DEVICE_SERIAL%
        echo DEVICE_NAME=%DEVICE_NAME%
        echo.
        echo # Gateway Configuration
        echo PORT=8787
        echo FASTAPI_URL=http://127.0.0.1:8000
        echo.
        echo # Local Operations
        echo AA_DRIVE_ROOT=%AA_SCRIPT_DRIVE%\
        echo AA_BACKUP_ON_WRITE=true
        echo AA_DRY_RUN_DEFAULT=false
        echo AA_QUICKSTART=true
        echo AA_PRELOAD_LB_CACHE=true
        echo.
        echo # Feature Flags
        echo V2_HOTKEY_LAUNCHER=false
    ) > .env

    echo [OK] Basic .env created
    echo [WARNING] You must add API keys manually to .env file!
    echo Required keys: ANTHROPIC_API_KEY, OPENAI_API_KEY, ELEVENLABS_API_KEY
) else (
    copy .env.template .env >nul

    REM Update device info in .env
    powershell -Command "(gc .env) -replace 'DEVICE_SERIAL=.*', 'DEVICE_SERIAL=%DEVICE_SERIAL%' | Out-File -encoding ASCII .env"
    powershell -Command "(gc .env) -replace 'DEVICE_NAME=.*', 'DEVICE_NAME=%DEVICE_NAME%' | Out-File -encoding ASCII .env"

    REM Generate AA_DEVICE_ID (UUID) and write to .env
    powershell -Command "$id=[guid]::NewGuid().ToString(); (gc .env) -replace 'AA_DEVICE_ID=.*', ('AA_DEVICE_ID=' + $id) | Out-File -encoding ASCII .env"

    REM Persist device manifest to drive_root\.aa\cabinet_manifest.json (uses AA_SCRIPT_DRIVE)
    powershell -Command "$root='%AA_SCRIPT_DRIVE%\'; $dir=Join-Path $root '.aa'; New-Item -ItemType Directory -Force -Path $dir | Out-Null; $mf=Join-Path $dir 'cabinet_manifest.json'; $envvars = Get-Content -Raw -Path '.env'; $aaid = ($envvars -split '\r?\n' | Where-Object { $_ -like 'AA_DEVICE_ID=*' } | ForEach-Object { ($_ -split '=',2)[1] }); $obj = @{ device_id=$aaid; serial='%DEVICE_SERIAL%'; name='%DEVICE_NAME%' }; ($obj | ConvertTo-Json) | Set-Content -LiteralPath $mf -Encoding UTF8"

echo [OK] .env file created from template
    echo [OK] Device serial and name configured
)

echo.
pause

REM ----------------------------------------
REM STEP 4: Install Node.js Dependencies
REM ----------------------------------------
echo.
echo [4/8] Installing Node.js dependencies...
echo This may take a few minutes...
echo.

call npm install
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to install root dependencies!
    pause
    exit /b 1
)

echo [OK] Root dependencies installed
echo.

REM ----------------------------------------
REM STEP 5: Install Frontend Dependencies
REM ----------------------------------------
echo.
echo [5/8] Installing frontend dependencies...
echo.

cd frontend
call npm install
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to install frontend dependencies!
    cd ..
    pause
    exit /b 1
)
cd ..

echo [OK] Frontend dependencies installed
echo.

REM ----------------------------------------
REM STEP 6: Install Backend Dependencies
REM ----------------------------------------
echo.
echo [6/8] Installing backend dependencies...
echo.

pip install -r backend\requirements.txt
if %ERRORLEVEL% NEQ 0 (
    echo [WARNING] Some backend dependencies may have failed to install
    echo Check the output above for errors
    echo.
    pause
)

echo [OK] Backend dependencies installed
echo.

REM ----------------------------------------
REM STEP 7: Create Desktop Shortcuts
REM ----------------------------------------
echo.
echo [7/8] Creating desktop shortcuts...
echo.

set DESKTOP=%USERPROFILE%\Desktop
set INSTALL_DIR=%CD%

REM Create Start Arcade Assistant shortcut
powershell -Command "$WS = New-Object -ComObject WScript.Shell; $SC = $WS.CreateShortcut('%DESKTOP%\Arcade Assistant.lnk'); $SC.TargetPath = '%INSTALL_DIR%\start-arcade-assistant.bat'; $SC.WorkingDirectory = '%INSTALL_DIR%'; $SC.IconLocation = '%INSTALL_DIR%\frontend\public\favicon.ico'; $SC.Description = 'Start Arcade Assistant Services'; $SC.Save()"

REM Create Open Arcade Assistant shortcut
powershell -Command "$WS = New-Object -ComObject WScript.Shell; $SC = $WS.CreateShortcut('%DESKTOP%\Open Arcade Assistant.lnk'); $SC.TargetPath = 'http://localhost:8787'; $SC.IconLocation = '%INSTALL_DIR%\frontend\public\favicon.ico'; $SC.Description = 'Open Arcade Assistant in Browser'; $SC.Save()"

if exist "%DESKTOP%\Arcade Assistant.lnk" (
    echo [OK] Desktop shortcut "Arcade Assistant" created
) else (
    echo [WARNING] Failed to create desktop shortcut
)

if exist "%DESKTOP%\Open Arcade Assistant.lnk" (
    echo [OK] Desktop shortcut "Open Arcade Assistant" created
) else (
    echo [WARNING] Failed to create desktop shortcut
)

echo.

REM ----------------------------------------
REM STEP 8: Final Summary
REM ----------------------------------------
echo.
echo ========================================
echo   INSTALLATION COMPLETE!
echo ========================================
echo.
echo Device Serial: %DEVICE_SERIAL%
echo Device Name: %DEVICE_NAME%
echo Install Location: %INSTALL_DIR%
echo.
echo ========================================
echo   NEXT STEPS:
echo ========================================
echo.
echo 1. IMPORTANT: Edit .env file and add your API keys:
echo    - ANTHROPIC_API_KEY (Claude AI)
echo    - OPENAI_API_KEY (GPT AI)
echo    - ELEVENLABS_API_KEY (Text-to-Speech)
echo.
echo 2. Double-click "Arcade Assistant" on your desktop
echo    This will start the backend and gateway services
echo.
echo 3. Wait 10 seconds, then double-click "Open Arcade Assistant"
echo    This will open the UI in your browser
echo.
echo 4. Test LaunchBox integration by asking LoRa about games
echo.
echo ========================================
echo   TROUBLESHOOTING:
echo ========================================
echo.
echo - If services don't start: Run start-arcade-assistant.bat as Administrator
echo - If browser shows errors: Check that A: drive is accessible
echo - If AI doesn't work: Verify API keys are in .env file
echo - See CABINET_TROUBLESHOOTING.md for more help
echo.
echo ========================================
echo.

REM Register installation in serial registry
echo %DATE% %TIME% - Cabinet %DEVICE_SERIAL% (%DEVICE_NAME%) installed at %INSTALL_DIR% >> SERIAL_REGISTRY.log

echo Installation log saved to SERIAL_REGISTRY.log
echo.
pause

echo Installation complete! Press any key to exit.
pause >nul
