#!/usr/bin/env python3
"""
Setup per-system bezels/overlays for RetroArch.

This script creates core-specific config files that enable system bezels
for each platform (NES, SNES, Genesis, etc.) instead of per-game bezels.

Usage:
    python setup_retroarch_bezels.py
"""

import os
from pathlib import Path

# RetroArch installation path
RETROARCH_ROOT = Path(os.environ.get("AA_DRIVE_ROOT", "A:\\")) / "Emulators" / "RetroArch"
RETROARCH_CONFIG = RETROARCH_ROOT / "config"
RETROARCH_OVERLAYS = RETROARCH_ROOT / "overlays"

# Mapping: Core name -> Overlay file (without extension)
# These map RetroArch cores to their corresponding system overlays
CORE_TO_OVERLAY = {
    # Atari
    "Stella": "Atari-2600",
    "Stella 2014": "Atari-2600",
    "Stella 2023": "Atari-2600",
    "ProSystem": "Atari-7800",
    "Virtual Jaguar": "Atari-Jaguar",
    "Handy": "Atari-Lynx-Horizontal",
    "Beetle Lynx": "Atari-Lynx-Horizontal",
    
    # Nintendo
    "FCEUmm": "Nintendo-Entertainment-System",
    "Nestopia": "Nintendo-Entertainment-System",
    "Mesen": "Nintendo-Entertainment-System",
    "QuickNES": "Nintendo-Entertainment-System",
    "Snes9x": "Super-Nintendo-Entertainment-System",
    "Snes9x 2010": "Super-Nintendo-Entertainment-System",
    "bsnes": "Super-Nintendo-Entertainment-System",
    "Gambatte": "Nintendo-Game-Boy",
    "SameBoy": "Nintendo-Game-Boy",
    "Gearboy": "Nintendo-Game-Boy",
    "TGB Dual": "Nintendo-Game-Boy",
    "mGBA": "Nintendo-Game-Boy-Advance",
    "VBA-M": "Nintendo-Game-Boy-Advance",
    "VBA Next": "Nintendo-Game-Boy-Advance",
    "gpSP": "Nintendo-Game-Boy-Advance",
    "Beetle GBA": "Nintendo-Game-Boy-Advance",
    "Mupen64Plus-Next": "Nintendo-64",
    "ParaLLEl N64": "Nintendo-64",
    "melonDS": "Nintendo-DS",
    "DeSmuME": "Nintendo-DS",
    
    # Sega
    "Genesis Plus GX": "Sega-Genesis",
    "PicoDrive": "Sega-Genesis",
    "BlastEm": "Sega-Genesis",
    "Gearsystem": "Sega-Master-System",
    "SMS Plus GX": "Sega-Master-System",
    "Beetle Saturn": "Sega-Saturn",
    "Yabause": "Sega-Saturn",
    "Kronos": "Sega-Saturn",
    "Flycast": "Dreamcast",
    "Reicast": "Dreamcast",
    
    # Sony
    "Beetle PSX": "Sony-PlayStation",
    "Beetle PSX HW": "Sony-PlayStation",
    "PCSX-ReARMed": "Sony-PlayStation",
    "SwanStation": "Sony-PlayStation",
    "PPSSPP": "Sony-PSP",
    
    # NEC
    "Beetle PCE Fast": "NEC-TurboGrafx-16",
    "Beetle PCE": "NEC-TurboGrafx-16",
    "Beetle SuperGrafx": "NEC-SuperGrafx",
    
    # SNK
    "FinalBurn Neo": "SNK-Neo-Geo-Horizontal",
    
    # Other
    "Beetle Cygne": "Bandai-WonderSwan-Horizontal",
    "Gearcoleco": "Colecovision",
    "blueMSX": "Microsoft-MSX",
    "fMSX": "Microsoft-MSX",
    "MAME": "MAME-Horizontal",
    "MAME 2003": "MAME-Horizontal",
    "MAME 2003-Plus": "MAME-Horizontal",
    "ScummVM": "ScummVM",
}


def get_overlay_path(overlay_name: str) -> Path:
    """Get the full path to an overlay config file."""
    return RETROARCH_OVERLAYS / f"{overlay_name}.cfg"


def create_core_config(core_name: str, overlay_name: str) -> bool:
    """Create or update a core config file with overlay settings."""
    core_dir = RETROARCH_CONFIG / core_name
    core_cfg = core_dir / f"{core_name}.cfg"
    
    # Ensure core directory exists
    core_dir.mkdir(parents=True, exist_ok=True)
    
    overlay_cfg_path = get_overlay_path(overlay_name)
    
    # Check if overlay exists
    if not overlay_cfg_path.exists():
        print(f"  ⚠ Overlay not found: {overlay_cfg_path}")
        return False
    
    # Config content for enabling overlay
    # Use forward slashes for RetroArch compatibility
    overlay_path_str = str(overlay_cfg_path).replace("\\", "/")
    
    config_lines = [
        f'# Auto-generated by Arcade Assistant - Per-system bezel config',
        f'# Core: {core_name}',
        f'# Overlay: {overlay_name}',
        f'',
        f'input_overlay_enable = "true"',
        f'input_overlay = "{overlay_path_str}"',
        f'input_overlay_opacity = "1.000000"',
        f'input_overlay_scale = "1.000000"',
        f'aspect_ratio_index = "22"',  # Core provided
        f'video_scale_integer = "false"',
    ]
    
    # Write config
    with open(core_cfg, 'w') as f:
        f.write('\n'.join(config_lines))
    
    print(f"  ✓ Created: {core_cfg.name}")
    return True


def main():
    print("=" * 60)
    print("RetroArch Per-System Bezel Setup")
    print("=" * 60)
    print(f"RetroArch Root: {RETROARCH_ROOT}")
    print(f"Config Dir: {RETROARCH_CONFIG}")
    print(f"Overlays Dir: {RETROARCH_OVERLAYS}")
    print()
    
    if not RETROARCH_ROOT.exists():
        print(f"ERROR: RetroArch not found at {RETROARCH_ROOT}")
        return 1
    
    if not RETROARCH_OVERLAYS.exists():
        print(f"ERROR: Overlays folder not found at {RETROARCH_OVERLAYS}")
        return 1
    
    # List available overlays
    available_overlays = [f.stem for f in RETROARCH_OVERLAYS.glob("*.cfg")]
    print(f"Found {len(available_overlays)} overlay configs")
    print()
    
    success_count = 0
    skip_count = 0
    
    print("Creating per-core bezel configs...")
    print("-" * 40)
    
    for core_name, overlay_name in sorted(CORE_TO_OVERLAY.items()):
        if overlay_name not in available_overlays:
            print(f"  ⚠ Skipping {core_name}: overlay '{overlay_name}' not available")
            skip_count += 1
            continue
        
        if create_core_config(core_name, overlay_name):
            success_count += 1
    
    print()
    print("=" * 60)
    print(f"Summary: {success_count} configs created, {skip_count} skipped")
    print("=" * 60)
    print()
    print("Done! Restart RetroArch for changes to take effect.")
    print()
    print("Note: These are per-CORE configs. All games using that core")
    print("will display the system bezel automatically.")
    
    return 0


if __name__ == "__main__":
    exit(main())
